SET search_path TO 'ubd_20202';

ALTER TABLE MEMBER

ADD CONSTRAINT FK_BAND FOREIGN KEY (id_band) REFERENCES BAND(id_band),
ADD CONSTRAINT FK_MUSICIAN FOREIGN KEY (id_musician) REFERENCES MUSICIAN(id_musician)
;