SET search_path TO 'ubd_20202';
ALTER TABLE member

ADD CONSTRAINT FK_BAND FOREIGN KEY (id_band) 
REFERENCES BAND(id_band)ON UPDATE CASCADE,

ADD CONSTRAINT FK_MUSICIAN FOREIGN KEY (id_musician) 
REFERENCES MUSICIAN(id_musician) ON UPDATE CASCADE
;