SET search_path TO 'ubd_20202';
ALTER TABLE COMPOSER

ADD CONSTRAINT FK_SONG FOREIGN KEY (id_song) 
REFERENCES SONG(id_SONG) ON UPDATE CASCADE,

DROP COLUMN year,
ADD COLUMN awards SMALLINT  default 0 NOT null
;