SET search_path TO 'ubd_20202';

CREATE TABLE SONG(
	id_song SMALLINT,
	title_song VARCHAR(255),
	duration TIME NOT NULL,
	id_album SMALLINT,
	CONSTRAINT PK_SONG PRIMARY KEY(id_song),
	CONSTRAINT FK_ALBUM FOREIGN KEY (id_album) REFERENCES ALBUM(id_album) ON UPDATE CASCADE);
COMMIT;